### ISSUE TITLE
Array to string conversion in Security.php on line 550

### ISSUE THREAD

**Issue by ramenknight** [marcocesarato/PHP-AIO-Security#10]
Hi Marco,

For some reason, I get the error "Array to string conversion in Security.php on line 550" just from a simple form with multiselection options, any idea how I can fix this issue?

Thanks,

**Comment by marcocesarato** [comment]
Hi,
you sure is line 550? There is a javascript code on that line then its impossible. Check on your file and le me know what is on that line.

**Comment by ramenknight** [comment]
on my line 550:

`$_REQUEST = array_unique(array_merge($_GET, $_POST, array_diff_assoc($_REQUEST, $_COOKIE)));`

It's on `public static function cleanGlobals()`

**Comment by marcocesarato** [comment]
Strange... anyways you can comment that line it is not perfectly necessary, it only increases the probability of finding what you are looking for also in $ _REQUEST. Try it and let me know if is solved

**Comment by ramenknight** [comment]
Commenting that line works... But doing that it's not going to decrease the security features of the class?

**Comment by marcocesarato** [comment]
You should replace it with `$_REQUEST= self::clean($_REQUEST, false, false);`
