### ISSUE TITLE
Working Very Slow

### ISSUE THREAD

**Issue by guddumodok** [marcocesarato/PHP-AIO-Security#11]
Respected Developers, Its work very slow and take times too to response.It always return Permission deny when user input some JS codes.

**Comment by marcocesarato** [comment]
> Its work very slow and take times too to response.

Depends what features you enabled, how much large are your pages and your server performance.

> It always return Permission deny when user input some JS codes.

Yes are considered XSS so dangerous for security and XSS is the most frequent issues on websites. If you want ignore it you must set `Security::$clean_post_xss` to false and user input must be sent only via POST requests (best practice vs XSS) or filtering it separately
