### ISSUE TITLE
Undefined index: _CSRFTOKEN

### ISSUE THREAD

**Issue by ramenknight** [marcocesarato/PHP-AIO-Security#4]
Hi Marco,

I'm trying to use your code but for some reason my forms just stop working when the class is activated, I keep getting the "_Undefined index: _CSRFTOKEN_" error on post request.

On this line:
```
$GLOBALS[self::$csrf_session . $csrf_key] = $_SESSION[self::$csrf_session . $csrf_key];
$token                                    = $GLOBALS[self::$csrf_session . $csrf_key];
```

Any idea what im doing wrong?

Thanks,

**Comment by marcocesarato** [comment]
I've disable temporary auto_csrf with a new setting. Now i will check better where the problem could be located.

**Comment by ramenknight** [comment]
Thank you Marco, please let me know if you find the issue.

**Comment by marcocesarato** [comment]
Fixed the issue. For use CSRF now must enable the setting `$auto_csrf` and nee to use like on the new test example the method `output`

**Comment by ramenknight** [comment]
It's working great now, thanks Marco.
