### ISSUE TITLE
Closing Session Issue

### ISSUE THREAD

**Issue by ramenknight** [marcocesarato/PHP-AIO-Security#6]
Hi Marco,

For some reason my logout stops working with the security class activated. Any idea why that is happening?

My logout code is:

```
session_start();
$_SESSION = array();
session_unset();
session_destroy();
header("location: index.php");
```

I also tried to delete the cookies with the code below but seems that it's not helping...

```
if (ini_get("session.use_cookies")) {
    $params = session_get_cookie_params();
    setcookie(session_name(), '', time() - 42000,
        $params["path"], $params["domain"],
        $params["secure"], $params["httponly"]
    );
}
```

Thanks.

**Comment by marcocesarato** [comment]
You need to start session with Security::secureSession(); because session_name is customized for don't be detected as php (Cookie PHPSESSID) then just do this:

```
Security::secureSession();
$_SESSION = array();
session_unset();
session_destroy();
header("location: index.php");
```

**Comment by ramenknight** [comment]
Thank you so much Marco.
