### ISSUE TITLE
Session Closing After 5 Seconds

### ISSUE THREAD

**Issue by ramenknight** [marcocesarato/PHP-AIO-Security#7]
Hi Marco,

For some reason sometimes the session closes too quickly (after 5 or 10 seconds). In the class Security the session lifetime is `public static $session_lifetime = 288000;`

Any idea why this is happening?

**Comment by marcocesarato** [comment]
This can happen with CSRF violation or with Hijacking violation (if you change your ip address, client etc...) I will verify thank you thanks for the tip

**Comment by ramenknight** [comment]
Seems that its a little random, sometimes I get logout really quick other times takes more time.

**Comment by ramenknight** [comment]
So after testing and disable some functions I think is related with the `function secureSession()`

Also if i try to put the auto_session_manager to true my login does not work, so i have the session start in my config file like this:
```
require_once("classes/Security.php");
Security::secureSession();
```

Do you think thats somehow creating the log out issue?

**Comment by marcocesarato** [comment]
Hi, I tried but couldn't replicate the problem.
The `auto_session_manager` do exactly `Security::secureSession()` you can check you have $session_regenerate_id option to false, you can check on your php.ini if is enabled the ini_set (not enabled sometimes) soon I will try others tests for try replicate the problem. You can try also use session on database (faster and more secure) passing a PDO object on option $database.

**Comment by ramenknight** [comment]
Thank you so much Marco,

Seems that the `$session_regenerate_id` option was creating the issue.
